# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import osi_groundtruth_pb2 as osi__groundtruth__pb2
import test_grpc_pb2 as test__grpc__pb2


class GroundtruthdataStub(object):
  # missing associated documentation comment in .proto file


  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProcessGThost = channel.unary_unary(
        '/osi3.Groundtruthdata/ProcessGThost',
        request_serializer=osi__groundtruth__pb2.GroundTruth.SerializeToString,
        response_deserializer=test__grpc__pb2.Empty.FromString,
        )
    self.ProcessGroundTruth = channel.unary_unary(
        '/osi3.Groundtruthdata/ProcessGroundTruth',
        request_serializer=osi__groundtruth__pb2.GroundTruth.SerializeToString,
        response_deserializer=test__grpc__pb2.Empty.FromString,
        )
    self.SayHello = channel.unary_unary(
        '/osi3.Groundtruthdata/SayHello',
        request_serializer=test__grpc__pb2.HelloRequest.SerializeToString,
        response_deserializer=test__grpc__pb2.HelloReply.FromString,
        )


class GroundtruthdataServicer(object):
  # missing associated documentation comment in .proto file


  def ProcessGThost(self, request, context):
    # missing associated documentation comment in .proto file

    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessGroundTruth(self, request, context):
    # missing associated documentation comment in .proto file

    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GroundtruthdataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProcessGThost': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessGThost,
          request_deserializer=osi__groundtruth__pb2.GroundTruth.FromString,
          response_serializer=test__grpc__pb2.Empty.SerializeToString,
      ),
      'ProcessGroundTruth': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessGroundTruth,
          request_deserializer=osi__groundtruth__pb2.GroundTruth.FromString,
          response_serializer=test__grpc__pb2.Empty.SerializeToString,
      ),
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=test__grpc__pb2.HelloRequest.FromString,
          response_serializer=test__grpc__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'osi3.Groundtruthdata', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
