# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import osi_groundtruth_pb2 as osi__groundtruth__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_grpc.proto',
  package='osi3',
  syntax='proto3',
  serialized_pb=_b('\n\x0ftest_grpc.proto\x12\x04osi3\x1a\x15osi_groundtruth.proto\"\x17\n\x05\x45mpty\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb0\x01\n\x0fGroundtruthdata\x12\x31\n\rProcessGThost\x12\x11.osi3.GroundTruth\x1a\x0b.osi3.Empty\"\x00\x12\x36\n\x12ProcessGroundTruth\x12\x11.osi3.GroundTruth\x1a\x0b.osi3.Empty\"\x00\x12\x32\n\x08SayHello\x12\x12.osi3.HelloRequest\x1a\x10.osi3.HelloReply\"\x00\x62\x06proto3')
  ,
  dependencies=[osi__groundtruth__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='osi3.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='osi3.Empty.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=71,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='osi3.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='osi3.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=101,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='osi3.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='osi3.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'test_grpc_pb2'
  # @@protoc_insertion_point(class_scope:osi3.Empty)
  ))
_sym_db.RegisterMessage(Empty)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'test_grpc_pb2'
  # @@protoc_insertion_point(class_scope:osi3.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'test_grpc_pb2'
  # @@protoc_insertion_point(class_scope:osi3.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)



_GROUNDTRUTHDATA = _descriptor.ServiceDescriptor(
  name='Groundtruthdata',
  full_name='osi3.Groundtruthdata',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=135,
  serialized_end=311,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessGThost',
    full_name='osi3.Groundtruthdata.ProcessGThost',
    index=0,
    containing_service=None,
    input_type=osi__groundtruth__pb2._GROUNDTRUTH,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ProcessGroundTruth',
    full_name='osi3.Groundtruthdata.ProcessGroundTruth',
    index=1,
    containing_service=None,
    input_type=osi__groundtruth__pb2._GROUNDTRUTH,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='osi3.Groundtruthdata.SayHello',
    index=2,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GROUNDTRUTHDATA)

DESCRIPTOR.services_by_name['Groundtruthdata'] = _GROUNDTRUTHDATA

# @@protoc_insertion_point(module_scope)
